/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logica.Operaciones;


/**
 *
 * @author Vinni
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.opDecimalIN.setSelected(true);
        this.opDecimalOUT.setSelected(true);
        numH(txtEntrada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoIn = new javax.swing.ButtonGroup();
        grupoOut = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        opOctalOUT = new javax.swing.JRadioButton();
        opDecimalOUT = new javax.swing.JRadioButton();
        opBinariolOUT = new javax.swing.JRadioButton();
        opHexaOUT = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSalida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JTextField();
        btProcesar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        opOctalN = new javax.swing.JRadioButton();
        opDecimalIN = new javax.swing.JRadioButton();
        opBinariolIN = new javax.swing.JRadioButton();
        opHexaIN = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resultado: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 390, 230, 30);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        grupoOut.add(opOctalOUT);
        opOctalOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opOctalOUT.setText("Octal");
        jPanel1.add(opOctalOUT);
        opOctalOUT.setBounds(20, 110, 110, 23);

        grupoOut.add(opDecimalOUT);
        opDecimalOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opDecimalOUT.setText("Decimal");
        jPanel1.add(opDecimalOUT);
        opDecimalOUT.setBounds(20, 20, 110, 25);

        grupoOut.add(opBinariolOUT);
        opBinariolOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opBinariolOUT.setText("Binario");
        jPanel1.add(opBinariolOUT);
        opBinariolOUT.setBounds(20, 50, 110, 23);

        grupoOut.add(opHexaOUT);
        opHexaOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opHexaOUT.setText("Hexadecimal");
        opHexaOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opHexaOUTActionPerformed(evt);
            }
        });
        jPanel1.add(opHexaOUT);
        opHexaOUT.setBounds(20, 80, 110, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(370, 130, 150, 150);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DISEÑADO POR GIOVANNI BRICEÑO : VINNI9@GAMAIL.COM 2023");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 450, 790, 10);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dato Salida");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 90, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dato Entrada");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 90, 180, 30);

        txtSalida.setBackground(new java.awt.Color(0, 0, 0));
        txtSalida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSalida.setForeground(new java.awt.Color(255, 255, 255));
        txtSalida.setText("----");
        txtSalida.setEnabled(false);
        txtSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSalida);
        txtSalida.setBounds(280, 390, 290, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Digite el número en base: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 340, 230, 30);

        txtEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(txtEntrada);
        txtEntrada.setBounds(280, 340, 290, 28);

        btProcesar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btProcesar.setForeground(new java.awt.Color(204, 0, 0));
        btProcesar.setText("PROCESAR");
        btProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcesarActionPerformed(evt);
            }
        });
        getContentPane().add(btProcesar);
        btProcesar.setBounds(590, 340, 150, 31);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        grupoIn.add(opOctalN);
        opOctalN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opOctalN.setText("Octal");
        opOctalN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opOctalNActionPerformed(evt);
            }
        });
        jPanel3.add(opOctalN);
        opOctalN.setBounds(20, 110, 110, 23);

        grupoIn.add(opDecimalIN);
        opDecimalIN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opDecimalIN.setText("Decimal");
        opDecimalIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDecimalINActionPerformed(evt);
            }
        });
        jPanel3.add(opDecimalIN);
        opDecimalIN.setBounds(20, 20, 110, 25);

        grupoIn.add(opBinariolIN);
        opBinariolIN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opBinariolIN.setText("Binario");
        opBinariolIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opBinariolINActionPerformed(evt);
            }
        });
        jPanel3.add(opBinariolIN);
        opBinariolIN.setBounds(20, 50, 110, 23);

        grupoIn.add(opHexaIN);
        opHexaIN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opHexaIN.setText("Hexadecimal");
        opHexaIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opHexaINActionPerformed(evt);
            }
        });
        jPanel3.add(opHexaIN);
        opHexaIN.setBounds(20, 80, 110, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(110, 130, 150, 150);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistemas numéricos");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 20, 260, 30);

        setSize(new java.awt.Dimension(807, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalidaActionPerformed

    private void txtEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaActionPerformed

    private void btProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcesarActionPerformed
        // TODO add your handling code here:
        validar();
        procesar();
    }//GEN-LAST:event_btProcesarActionPerformed

    private void opHexaOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opHexaOUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opHexaOUTActionPerformed

    private void opHexaINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opHexaINActionPerformed
        txtEntrada.setText("");
        //numH(txtEntrada);
    }//GEN-LAST:event_opHexaINActionPerformed

    private void opDecimalINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDecimalINActionPerformed
        txtEntrada.setText("");
        //numD(txtEntrada);
    }//GEN-LAST:event_opDecimalINActionPerformed

    private void opBinariolINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opBinariolINActionPerformed
        txtEntrada.setText("");
        //numB(txtEntrada);
    }//GEN-LAST:event_opBinariolINActionPerformed

    private void opOctalNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opOctalNActionPerformed
        
        txtEntrada.setText("");
        //numO(txtEntrada);
    }//GEN-LAST:event_opOctalNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProcesar;
    private javax.swing.ButtonGroup grupoIn;
    private javax.swing.ButtonGroup grupoOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton opBinariolIN;
    private javax.swing.JRadioButton opBinariolOUT;
    private javax.swing.JRadioButton opDecimalIN;
    private javax.swing.JRadioButton opDecimalOUT;
    private javax.swing.JRadioButton opHexaIN;
    private javax.swing.JRadioButton opHexaOUT;
    private javax.swing.JRadioButton opOctalN;
    private javax.swing.JRadioButton opOctalOUT;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
private void validar() {
    if(this.opBinariolIN.isSelected()){
        if(!validarB(txtEntrada.getText())){
            JOptionPane.showMessageDialog(rootPane,"Los datos no son correctos");
        }
    }
    if(this.opOctalN.isSelected()){
        if(!validarO(txtEntrada.getText())){
            JOptionPane.showMessageDialog(rootPane,"Los datos no son correctos");
        }
    }
    if(this.opDecimalIN.isSelected()){
        if(!validarD(txtEntrada.getText())){
            JOptionPane.showMessageDialog(rootPane,"Los datos no son correctos");
        }
    }
}
public static boolean validarB(String datos){
    return datos.matches("[0-1]*");
}
public static boolean validarO(String datos){
    return datos.matches("[0-7]*");
}
public static boolean validarD(String datos){
    return datos.matches("[0-9]*");
}

    private void procesar() {
        Operaciones operaciones = new Operaciones();
        if (this.txtEntrada.getText().isEmpty()){
            this.generarMensajeWarning("No hay numero de entrada");
            return ;
        }
        if (this.opDecimalIN.isSelected() && this.opBinariolOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirDecimalBinario(Integer.parseInt(txtEntrada.getText())));
        }
        if (this.opDecimalIN.isSelected() && this.opOctalOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirDecimalOctal(Integer.parseInt(txtEntrada.getText())));
        }
        if (this.opDecimalIN.isSelected() && this.opDecimalOUT.isSelected()){
            this.txtSalida.setText(this.txtEntrada.getText());
        }
        if (this.opDecimalIN.isSelected() && this.opHexaOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirDecimalHexadecimal(Integer.parseInt(txtEntrada.getText())));
        }
        if (this.opBinariolIN.isSelected() && this.opBinariolOUT.isSelected()){
            this.txtSalida.setText(this.txtEntrada.getText());
        }
        if (this.opBinariolIN.isSelected() && this.opDecimalOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirBinarioDecimal(Integer.parseInt(txtEntrada.getText())));
        }
        if (this.opBinariolIN.isSelected() && this.opOctalOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirBinarioOctal(Integer.parseInt(txtEntrada.getText())));
        }
        if (this.opBinariolIN.isSelected() && this.opHexaOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirBinarioHexadecimal(Integer.parseInt(txtEntrada.getText())));
        }
        if (this.opOctalN.isSelected() && this.opBinariolOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirOctalBinario(Integer.parseInt(txtEntrada.getText())));
        }
        if (this.opOctalN.isSelected() && this.opDecimalOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirOctalDecimal(Integer.parseInt(txtEntrada.getText())));
        }
        if (this.opOctalN.isSelected() && this.opHexaOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirOctalHexadecimal(Integer.parseInt(txtEntrada.getText())));
        }
        if (this.opOctalN.isSelected() && this.opOctalOUT.isSelected()){
            this.txtSalida.setText(this.txtEntrada.getText());
        }
        if (this.opHexaIN.isSelected() && this.opBinariolOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirHexadecimalBinario(txtEntrada.getText()));
        }
        if (this.opHexaIN.isSelected() && this.opDecimalOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirHexadecimalDecimal(txtEntrada.getText()));
        }
        if (this.opHexaIN.isSelected() && this.opOctalOUT.isSelected()){
            this.txtSalida.setText(operaciones.convertirHexadecimalOctal(txtEntrada.getText()));
        }
        if (this.opHexaIN.isSelected() && this.opHexaOUT.isSelected()){
            this.txtSalida.setText(this.txtEntrada.getText());
        }
    }
    private void generarMensajeOk(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    private void generarMensajeWarning(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.WARNING_MESSAGE);
    }
    
    private void numH(JTextField a){
    a.addKeyListener(new KeyAdapter() {
    public void keyTyped(KeyEvent e){
        char c = e.getKeyChar();
        if(!Character.isDigit(c) && c!='a' && c!='b' && c!='c' && c!='d' 
                && c!='e' && c!='f' && c!='A' 
                && c!='B' && c!='C' && c!='D'
                && c!='E' && c!='F'){
            e.consume();
        }
        
        /*if(c == '.' && txtEntrada.getText().contains(".")){
            e.consume();
        }*/
    }
});
}
    /*private void numD(JTextField b){
    b.addKeyListener(new KeyAdapter() {
    public void keyTyped(KeyEvent z){
        char d = z.getKeyChar();
        if(!Character.isDigit(d)){
            z.consume();
        }
    }
});
}
    
private void numO(JTextField c){
    c.addKeyListener(new KeyAdapter() {
    public void keyTyped(KeyEvent y){
        char o = y.getKeyChar();
        if(o!='0' && o!='1' && o!='2' && o!='3' && o!='4' && o!='5' && o!='6' && o!='7'){
            y.consume();
        }
    }
});
}

private void numB(JTextField a){
    a.addKeyListener(new KeyAdapter() {
    public void keyTyped(KeyEvent e){
        char c = e.getKeyChar();
        if(c!='0' && c!='1'){
            e.consume();
        }
    }
});
}*/

    
}